import Image from "next/image";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Footer, Header } from "@/components/site-chrome";
import { AddProductButton, FavouriteButton } from "@/components/product-actions";
import { getCatalogProducts, getProductRecord, getRelatedProducts } from "@/lib/catalog";
import "./product-detail.css";
import "./product-light.css";

export default async function ProductDetail({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const product=await getProductRecord(slug); if(!product&&slug==="signature-linen"){const current=await getCatalogProducts("bedding");if(current[0])redirect(`/product/${current[0].slug}`)} if(!product) notFound();
  const related=await getRelatedProducts(product._id); const images=product.images||[]; const primary=images.find(image=>image.isPrimary)||images[0]; if(!primary) notFound();
  const category=typeof product.category==="string"?"Collection":product.category.name; const subcategory=typeof product.subCategory==="string"?"":product.subCategory?.name||"";
  const cartItem={id:product._id,name:product.title,price:product.basePrice,image:primary.url,variant:`${product.colors[0]?.name||product.fabricType} · ${product.standardSizes[0]||"Standard"}`};
  const bundleTotal=(product.bundleItems||[]).reduce((sum,item)=>sum+item.price,product.basePrice);
  return <div className="detail-page"><Header/><main>
    <section className="detail-top"><div className="detail-gallery"><div className="detail-main-img"><Image src={primary.url} alt={primary.alt||product.title} fill priority quality={92} sizes="60vw"/><FavouriteButton item={cartItem}/></div><div className="detail-thumbs">{images.map(image=><Image key={image.url} src={image.url} alt={image.alt||product.title} width={150} height={110}/>)}</div></div>
      <div className="detail-config"><div className="detail-breadcrumb">HOME / {category.toUpperCase()} {subcategory?`/ ${subcategory.toUpperCase()}`:""}</div><span>{product.fabricType.toUpperCase()} ATELIER</span><h1>{product.title}</h1><div className="detail-rating">★★★★★ &nbsp; {product.ratingCount||0} REVIEWS</div><h3>From ${product.basePrice}</h3><p>{product.description}</p><label>SELECT COLOR — {product.colors[0]?.name?.toUpperCase()}</label><div className="detail-swatches">{product.colors.map(color=><i title={color.name} key={color.name} style={{background:color.hexCode}}/>)}</div><div className="detail-price-row"><b>SIZE</b><span>FROM ${product.basePrice}.00</span></div><div className="detail-sizes">{product.standardSizes.map((size,index)=><button className={index===0?"active":""} key={size}>{size}</button>)}</div><button className="detail-continue">CONTINUE</button>
        <section className="bundle-builder"><header><span>COMPLETE THE LOOK</span><h2>CREATE YOUR BUNDLE</h2><p>Select coordinating pieces managed with this product in the catalog.</p></header>{product.bundleItems?.map(item=><article key={item.name}><input type="checkbox" defaultChecked={item.selected}/><Image src={item.image} alt={item.name} width={72} height={72}/><div><h4>{item.name}</h4><small>{item.variant}</small><div className="mini-swatches">{product.colors.slice(0,3).map(()=>"○").join(" ")}</div></div><div className="bundle-controls"><b>${item.price}.00</b><select>{product.standardSizes.slice(0,3).map(size=><option key={size}>{size}</option>)}</select><span>− &nbsp; 1 &nbsp; +</span></div></article>)}<div className="bundle-total"><span>COMPLETE BUNDLE<small>{(product.bundleItems?.length||0)+1} coordinated pieces</small></span><b>${bundleTotal.toFixed(2)}</b></div><AddProductButton item={cartItem} bundle bundlePrice={bundleTotal}/><AddProductButton item={cartItem}/></section>
      </div></section>
    <section className="detail-benefits"><h2>Why You’ll Love It</h2><div>{product.benefits?.map(benefit=><article key={benefit.title}><i>{benefit.icon}</i><h3>{benefit.title}</h3><p>{benefit.description}</p></article>)}</div></section>
    <section className="spec-section"><div><h2>Technical Specifications</h2>{[["Material Composition",product.materialComposition],["Weave Construction",product.weaveConstruction],["Finishing Process",product.finishingProcess],["Origin & Craft",product.origin],["Weight",product.weight]].filter(([,value])=>value).map(([label,value])=><p key={label}><span>{label}</span><b>{value}</b></p>)}<h4>FEATURES & COMPLIANCE</h4><small>{product.features.join(" · ")}</small></div><div><h2>Product Dimensions</h2><table><thead><tr><th>SIZE</th><th>METRIC</th><th>IMPERIAL</th></tr></thead><tbody>{product.dimensions?.map(row=><tr key={row.size}><td>{row.size}</td><td>{row.metric}</td><td>{row.imperial}</td></tr>)}</tbody></table><h4>CARE INSTRUCTIONS</h4><div className="care-icons">{product.careInstructions?.map((care,index)=><span key={care}>{["▣","♨","◇","○"][index%4]}<small>{care}</small></span>)}</div></div></section>
    <section className="delivery-section"><div><h2>Delivery Estimate</h2><label>Enter Pincode <button>CHECK</button></label><p>Enter your pincode to view production and delivery estimates for this product.</p></div><div><h3>Inventory & Availability</h3><p>{product.inventoryCount} units currently available · Status: {product.stockStatus.replaceAll("_"," ")}.</p><h3>Complimentary Delivery</h3><p>Every order is inspected, carefully wrapped and dispatched from our atelier.</p><h3>Considered Returns</h3><p>Eligible standard-size pieces may be returned in their original condition.</p></div></section>
    <section className="craft-detail"><div><span>{product.editorial?.eyebrow}</span><h2>{product.editorial?.title}</h2><p>{product.editorial?.description}</p><ul><li>{product.materialComposition}</li>{product.features.map(feature=><li key={feature}>{feature}</li>)}</ul></div>{product.editorial?.image&&<Image src={product.editorial.image} alt={product.editorial.title||product.title} width={600} height={600}/>}</section>
    <section className="detail-recs"><div className="detail-section-head"><div><span>COMPLETE YOUR ROOM</span><h2>You May Also Like</h2><p>Products selected from the same category and material family.</p></div><b>← &nbsp; →</b></div><div>{related.map(item=>{const image=item.images.find(x=>x.isPrimary)||item.images[0];return image?<Link href={`/product/${item.slug}`} key={item._id}><div><Image src={image.url} alt={image.alt||item.title} fill sizes="25vw"/><button>♡</button></div><span>{typeof item.category==="string"?category:item.category.name}</span><h3>{item.title}</h3><p>From ${item.basePrice}</p><small>{item.colors.length} colours</small></Link>:null})}</div></section>
    <section className="reviews"><div className="detail-section-head"><div><span>AUTHENTIC STORIES FROM REAL HOMES</span><h2>Customer Reviews</h2></div><button>WRITE A REVIEW</button></div><div className="review-gallery">{images.slice(0,5).map(image=><Image key={image.url} src={image.url} alt={image.alt||product.title} width={230} height={150}/>)}</div><div className="review-body"><aside><b>{product.ratingAverage||"—"}</b><div>★★★★★</div><p>{product.ratingCount||0} REVIEWS</p></aside><div>{product.reviews?.map(review=><article key={`${review.title}-${review.date}`}><div>{"★".repeat(review.rating)} <span>{review.date}</span></div><h3>{review.title}</h3><p>{review.body}</p><small>{review.author}</small></article>)}</div></div></section>
    <section className="faq"><h2>Frequently Asked Questions</h2>{product.faqs?.map(item=><details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</section>
  </main><Footer/></div>;
}
