import Image from "next/image";
import Link from "next/link";
import { Footer, Header } from "@/components/site-chrome";
import "./product-detail.css";
import "./product-light.css";
import { AddProductButton, FavouriteButton } from "@/components/product-actions";

const bundle=[
  ["/figma/home-15.jpeg","Belgian Linen Tailored Bed Skirt","420"],["/figma/home-05.png","European Flax Linen Fitted Sheet","180"],
  ["/figma/home-10.jpeg","Velvet Envelope Shams Pair","165"],["/figma/home-17.jpeg","Garment-Washed Duvet Set","345"],
  ["/figma/home-18.jpeg","Architectural Border Quilt","275"],
];
const recommendations=[
  ["/figma/home-11.png","European Flax Linen Blanket","235"],["/figma/home-05.png","Waffle Weave Linen Coverlet","185"],
  ["/figma/home-15.jpeg","Garment-Washed Duvet Set","345"],["/figma/home-17.jpeg","Bespoke Linen Quilt","420"],
];

export default function ProductDetail(){return <div className="detail-page"><Header/><main>
  <section className="detail-top">
    <div className="detail-gallery"><div className="detail-main-img"><Image src="/figma/home-15.jpeg" alt="Linen blend bedspread" fill priority sizes="60vw"/><FavouriteButton/></div><div className="detail-thumbs">{["/figma/home-15.jpeg","/figma/home-05.png","/figma/home-03.jpeg","/figma/home-12.jpeg","/figma/home-18.jpeg"].map(src=><Image key={src} src={src} alt="Product view" width={150} height={110}/>)}</div></div>
    <div className="detail-config"><div className="detail-breadcrumb">HOME / BEDDING / BEDSPREADS</div><span>THE LINEN ATELIER</span><h1>Linen Blend Bedspread</h1><div className="detail-rating">★★★★★ &nbsp; 148 REVIEWS</div><h3>From $430</h3><p>Woven from a masterfully balanced blend of European flax linen and organic cotton, offering rich natural drape with quiet texture and exceptional softness. Designed for effortless layering and everyday luxury.</p><label>SELECT COLOR — NATURAL</label><div className="detail-swatches">{["#d8b092","#d9d2c4","#eee9df","#a39c8d","#b5ada1","#718078","#596a71","#89a0aa"].map(c=><i key={c} style={{background:c}}/>)}</div><div className="detail-price-row"><b>SIZE</b><span>FROM $430.00</span></div><div className="detail-sizes">{["Twin","Double","King","Super King","Custom Size"].map((x,i)=><button className={i===2?"active":""} key={x}>{x}</button>)}</div><button className="detail-continue">CONTINUE</button>
      <section className="bundle-builder"><header><span>STEP 2 OF 2</span><h2>CREATE YOUR BEDDING BUNDLE</h2><p>Select the pieces and quantities you need. Save 10% when you complete the look.</p></header>{bundle.map((x,i)=><article key={x[1]}><input type="checkbox" defaultChecked={i<2}/><Image src={x[0]} alt={x[1]} width={72} height={72}/><div><h4>{x[1]}</h4><small>Natural · European Linen</small><div className="mini-swatches">○ ● ○</div></div><div className="bundle-controls"><b>${x[2]}.00</b><select><option>King</option><option>Queen</option></select><span>− &nbsp; 1 &nbsp; +</span></div></article>)}<div className="bundle-total"><span>YOUR COMPLETE BEDDING BUNDLE<small>Includes 5 selected pieces</small></span><b>$432.00</b></div><AddProductButton bundle/><AddProductButton/></section>
    </div>
  </section>

  <section className="detail-benefits"><h2>Why You’ll Love It</h2><div>{[["♧","Breathable","Naturally regulates temperature for year-round comfort."],["≈","Softer Over Time","Grows softer and more supple with every wash."],["×","Impeccably Finished","Double stitching and premium edging for longevity."],["○","Effortless Layering","Perfect weight to dress beautifully over any bed."]].map(([i,h,p])=><article key={h}><i>{i}</i><h3>{h}</h3><p>{p}</p></article>)}</div></section>

  <section className="spec-section"><div><h2>Technical Specifications</h2>{[["Material Composition","55% European Flax Linen, 45% Long-Staple Cotton"],["Weave Construction","Yarn-dyed basket weave"],["Finishing Process","Garment washed for immediate softness"],["Origin & Craft","Jaipur, India · Master Atelier"],["Weight","260 GSM balanced year-round weight"]].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}<h4>FEATURES & COMPLIANCE</h4><small>OEKO-TEX Standard 100 Certified · Free from harmful substances · Responsibly manufactured.</small></div><div><h2>Bedspread Dimensions</h2><table><thead><tr><th>SIZE</th><th>BEDSPREAD SIZE</th><th>INCHES</th></tr></thead><tbody>{[["King","275 × 270 cm","108 × 106"],["Queen","240 × 260 cm","94 × 102"],["Double","220 × 240 cm","87 × 94"],["Super King","300 × 275 cm","118 × 108"]].map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table><h4>CARE INSTRUCTIONS</h4><div className="care-icons"><span>▣<small>Machine wash</small></span><span>♨<small>Low tumble dry</small></span><span>◇<small>Warm iron</small></span><span>○<small>Do not bleach</small></span></div></div></section>

  <section className="delivery-section"><div><h2>Delivery Estimate</h2><label>Enter Pincode <button>CHECK</button></label><p>Enter your pincode to view estimated delivery dates and shipping options available to your location.</p></div><div><h3>Free Shipping</h3><p>We are pleased to offer complimentary white-glove standard shipping on all orders worldwide. Made-to-order pieces are carefully wrapped and dispatched within our estimated production window.</p><h3>Free 30-Day Returns</h3><p>We offer free returns, and refund within 30 days of delivery for pieces in their original condition.</p><h3>Made in Harmony</h3><p>Your bespoke piece is crafted by artisans and inspected by hand before leaving our atelier.</p></div></section>

  <section className="craft-detail"><div><span>THE ATELIER</span><h2>Crafted with Intention</h2><p>Our signature blend achieves what pure linen cannot: immediate softness and fluid drape. By combining 55% premium European flax with 45% long-staple cotton, we created a textile that breathes effortlessly while maintaining a structured, comforting weight.</p><ul><li>55% European Flax Linen</li><li>45% Long-Staple Cotton</li><li>Garment Washed for Softness</li><li>Yarn-dyed for lasting colour</li></ul></div><Image src="/figma/home-03.jpeg" alt="Natural linen texture" width={600} height={600}/></section>

  <section className="detail-recs"><div className="detail-section-head"><div><span>COMPLETE YOUR BEDROOM</span><h2>You May Also Like</h2><p>Complementary bedding and accessories hand-crafted from our signature European yarns.</p></div><b>← &nbsp; →</b></div><div>{recommendations.map(x=><Link href="/product/signature-linen" key={x[1]}><div><Image src={x[0]} alt={x[1]} fill sizes="25vw"/><button>♡</button></div><span>BEDDING</span><h3>{x[1]}</h3><p>From ${x[2]}</p><small>○ ○ ○ &nbsp; +4</small></Link>)}</div></section>

  <section className="shop-look"><div><span>THE PRIMARY SUITE</span><h2>Shop The Look</h2><p>Complete your entire bedroom with a considered edit of accompanying bedlinen and accessories.</p><div className="look-photo"><Image src="/figma/home-15.jpeg" alt="The Primary Suite look" fill sizes="65vw"/>{["20% 35%","65% 20%","73% 65%","44% 72%"].map((p,i)=>{const [l,t]=p.split(" ");return <i key={p} style={{left:l,top:t}}>{i+1}</i>})}</div></div><aside><header><div><span>THE PRIMARY SUITE LOOK</span><h3>The Primary Suite Look</h3><p>Effortless layering in natural linen.</p></div><small>5 PIECES</small></header>{bundle.slice(0,4).map(x=><article key={x[1]}><Image src={x[0]} alt="" width={60} height={60}/><span>{x[1]}<small>Natural · King</small></span><b>${x[2]}</b></article>)}<div className="look-total"><span>Complete 5-Piece Ensemble</span><b>$1,227.50</b></div><button>ADD COMPLETE LOOK TO CART — SAVE 10%</button></aside></section>

  <section className="reviews"><div className="detail-section-head"><div><span>AUTHENTIC STORIES FROM REAL HOMES</span><h2>Customer Reviews</h2></div><button>WRITE A REVIEW</button></div><div className="review-gallery">{["/figma/home-15.jpeg","/figma/home-10.jpeg","/figma/home-05.png","/figma/home-11.png","/figma/home-17.jpeg"].map(src=><Image key={src} src={src} alt="Customer bedroom" width={230} height={150}/>)}</div><div className="review-body"><aside><b>4.8</b><div>★★★★★</div><p>148 REVIEWS</p>{[90,65,28,12,4].map((n,i)=><label key={i}>{5-i}<i><span style={{width:`${n}%`}}/></i></label>)}</aside><div>{[["Perfect weight and ethereal drape","The bedspread is truly exceptional. The linen blend is both softer than pure linen and has a beautiful, relaxed texture."],["Exceptional tailoring and heirloom craftsmanship","The stitching and finish are impeccable. It completely transformed our bedroom."],["Washes beautifully with zero shrinkage","I have machine-washed it twice and it becomes even softer every time."],["The SIZE chart is perfection","The drop is exactly right and the custom finish looks considered from every angle."]].map(([h,p],i)=><article key={h}><div>★★★★★ <span>28 SEP 2026</span></div><h3>{h}</h3><p>{p}</p><small>Verified Buyer · Helpful? Yes</small></article>)}</div></div></section>

  <section className="faq"><h2>Frequently Asked Questions</h2>{["What is the difference between this and pure linen?","How much will it shrink after washing?","Will it require ironing?","Do you offer custom sizes?","Is this suitable for sensitive skin?"].map(x=><details key={x}><summary>{x}<span>+</span></summary><p>Our atelier team has selected materials and finishes that balance comfort, longevity and effortless care.</p></details>)}</section>
  </main><Footer/></div>}
