"use client";
import {useState} from "react";
import Image from "next/image";
import Link from "next/link";
import { Footer, Header } from "@/components/site-chrome";
import "./fabric.css";

const fabrics=[
  ["/figma/home-02.png","White Linen","A"],["/figma/home-18.jpeg","Clay Linen","A"],["/figma/home-07.jpeg","Slate Wool","B"],["/figma/home-03.jpeg","Oatmeal Linen","A"],["/figma/home-04.jpeg","Sand Wool Blend","B"],["/figma/home-17.jpeg","Sky Cotton","A"],["/figma/home-12.jpeg","Terracotta Cotton","A"],["/figma/home-15.jpeg","Sage Linen","A"],["/figma/home-13.png","Forest Velvet","C"],["/figma/home-06.jpeg","Charcoal Velvet","C"],
];
export default function FabricStep(){const [modal,setModal]=useState(false);return <div className="fabric-step"><Header/><main><header><span>CUSTOM DRAPERY</span><h1>Ripple Fold Drapery</h1></header><section className="collection"><h2>01 — CHOOSE YOUR COLLECTION</h2><div>{["LINENS","SHEERS","WOOLS + BLENDS","COTTONS","SILKS","SOLIDS","PATTERNS","KIDS","DESIGNERS","SUNBRELLA","MOST POPULAR"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div><nav><span>Collection⌄</span><span>Color⌄</span><span>Price⌄</span><span>Material⌄</span><span>SORT ↕</span></nav></section><section className="materials"><h2>02 — SELECT MATERIAL &amp; COLOR</h2>{["LINENS & NATURAL WEAVES","COTTON & BLENDS"].map(group=><div className="material-group" key={group}><h3>MATERIAL: {group} <i/> PRICE GROUP: A <i/> FROM: $650</h3><p>Soft, breathable and wonderfully versatile, long-staple fibres bring understated everyday elegance to both classic architectural spaces and contemporary interiors.</p><div>{fabrics.map(([src,name,price],i)=><button className={i===3?"selected":""} key={`${group}-${name}`} onClick={()=>setModal(true)}><span><Image src={src} alt={name} fill sizes="16vw"/><i>⌕</i>{i===3&&<b>✓</b>}</span><strong>{name}</strong><small>Price Group {price}</small></button>)}</div></div>)}</section></main><div className="fabric-bar"><div><b>RIPPLE FOLD DRAPERY</b><span>Linen · Oatmeal</span></div><strong>Price from $770</strong><Link href="/drapery/configure/details">CONTINUE TO MOUNT &amp; CONFIGURATION&nbsp; →</Link></div><Footer/>{modal&&<div className="fabric-modal-backdrop" onClick={()=>setModal(false)}><section className="fabric-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(false)}>×</button><div className="modal-photo"><Image src="/figma/home-03.jpeg" alt="Oatmeal linen closeup" fill sizes="50vw"/><i>⌕</i></div><div className="modal-copy"><span>PRICE GROUP A</span><h2>Oatmeal Linen</h2><p>A classic Belgian linen in a warm oatmeal hue, woven with a rich slub texture and soft fluid drape. Breathable, durable, and naturally elegant — designed for timeless interiors with effortless light filtering.</p><hr/>{[["COMPOSITION","100% Belgian Flax Linen"],["WEIGHT","320 GSM (Heavyweight Architectural Drape)"],["DURABILITY","30,000 Martindale Rubs (Commercial Grade)"],["LIGHT FILTERING","Semi-Sheer to Light Filtering (Soft Glow)"]].map(([a,b])=><dl key={a}><dt>{a}</dt><dd>{b}</dd></dl>)}<span>CARE &amp; MAINTENANCE</span><p>Ⓟ &nbsp; ▱ &nbsp; △ &nbsp; Professional dry clean or steam in situ.</p><button onClick={()=>setModal(false)}>SELECT THIS FABRIC →</button><button className="swatch-add">＋ ADD TO SWATCHES</button><div className="swatch-rate"><b>BASE SWATCH SET</b><strong>$20 Flat Rate</strong><span>Includes up to 4 swatches</span><span>1 of 4 selected</span></div></div></section></div>}</div>}
