import Image from "next/image";
import Link from "next/link";
import { Footer, Header } from "@/components/site-chrome";
import "./details.css";

const groups=[
  ["02","SELECT MOUNT & POSITION",["INSIDE MOUNT","OUTSIDE MOUNT","CEILING MOUNT"]],
  ["03","CHOOSE YOUR LINING",["UNLINED","COTTON LINING","BLACKOUT LINING"]],
  ["04","RODS, RAILS & MOTORIZED SYSTEMS",["CLASSIC ROD","TRAVERSE ROD","MOTORIZED TRACK"]],
  ["05","SELECT DRAPERY HARDWARE",["MATTE BLACK","ANTIQUE BRASS","SATIN NICKEL","DARK BRONZE"]],
  ["06","EMBROIDERED TRIMS",["CLEAN FINISH","CLASSIC BORDER","ORNATE BORDER"]],
  ["07","VALANCE CONFIGURATION",["NO VALANCE","UPHOLSTERED CORNICE","SOFT VALANCE"]],
  ["08","TIE BACKS",["STRAIGHT TIEBACK","SCULPTED TIEBACK"]],
];
export default function Details(){return <div className="details-step"><Header/><main><header><span>CUSTOM DRAPERY</span><h1>Pinch Pleat Drapery</h1></header><div className="details-layout"><aside><Image src="/figma/home-01.jpeg" alt="Pinch pleat drapery preview" fill priority sizes="45vw"/></aside><section><div className="config-section measurements"><div className="section-label"><b>01</b><span>FINAL CONFIGURATION</span><small>Digital Step 1</small></div><h2>YOUR MEASUREMENTS</h2><p>Enter your finished dimensions or schedule a complimentary measure consultation.</p><div className="measurement-grid"><label>WINDOW WIDTH<input placeholder="120"/><small>inches</small></label><label>FINISHED LENGTH<input placeholder="96"/><small>inches</small></label><label>NUMBER OF PANELS<select><option>Pair (2 panels)</option></select></label><label>FULLNESS<select><option>2.5× Fullness</option></select></label></div></div>{groups.map(([n,title,options],index)=><div className="config-section" key={title as string}><div className="section-label"><b>{n as string}</b><span>{title as string}</span><small>Selected: {index===0?"Outside Mount":"Classic"}</small></div><div className="option-grid">{(options as string[]).map((x,i)=><label className={i===0?"selected":""} key={x}><input type="radio" name={title as string} defaultChecked={i===0}/><div className="option-visual">{index===1?<Image src={["/figma/home-19.png","/figma/home-03.jpeg","/figma/home-12.jpeg"][i]} alt="" fill sizes="12vw"/>:<span>{index===3?["●","●","●","●"][i]:"▥"}</span>}</div><b>{x}</b><small>{index===2?"Tailored for smooth operation":"Recommended for this style"}</small></label>)}</div>{index===3&&<div className="finish-swatches">{["#bd9a47","#272727","#88847d","#6d5745","#ddd6c5","#857b69"].map(c=><i key={c} style={{background:c}}/>)}</div>}{index===4&&<div className="trim-feature"><Image src="/figma/home-04.jpeg" alt="Trim detail" width={180} height={130}/><div><h3>Champagne Ivory Tassel</h3><p>Hand-finished decorative trim with a soft architectural drape.</p></div></div>}</div>)}<div className="config-section final-summary"><h2>YOUR CUSTOM DRAPERY</h2><p>Pinch Pleat · Oatmeal Linen · Blackout Lining · Antique Brass</p><div><span>Estimated price</span><b>$545.00</b></div><button>ADD TO CART</button></div></section></div></main><div className="detail-bottom-bar"><span>YOUR CUSTOM DRAPERY<small>Ripple Fold · Beige Flax · Wall Mount · Pair</small></span><b>$545.00</b><button>ADD TO CART</button></div><Footer/></div>}
